### ISSUE TITLE
Breaking sidecar translations.

### ISSUE THREAD

**Issue by andrzejsliwa** [palkan/view_component-contrib#29]
## What did you do?

I just added sidecar translations, because for my use case they are perfect.

## What did you expect to happen?

to run without errors

## What actually happened?

NoMethodError: undefined method `to_sym' for ["example"]:Array

[view_component (2.80.0) lib/view_component/translatable.rb:44:in `map'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/translatable.rb:44:in `initialize'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/translatable.rb:32:in `new'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/translatable.rb:32:in `build_i18n_backend'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/compiler.rb:79:in `compile'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/base.rb:518:in `compile'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/base.rb:95:in `render_in'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/instrumentation.rb:19:in `block in render_in'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[activesupport (7.0.4) lib/active_support/notifications.rb:206:in `block in instrument'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[activesupport (7.0.4) lib/active_support/notifications/instrumenter.rb:24:in `instrument'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[activesupport (7.0.4) lib/active_support/notifications.rb:206:in `instrument'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[view_component (2.80.0) lib/view_component/instrumentation.rb:12:in `render_in'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
[actionview (7.0.4) lib/action_view/helpers/rendering_helper.rb:42:in `render'](http://localhost:3000/lanes/1/slots/1?start_date=2023-01-24#)
## Additional context

it's happening because by default, your base class in including TranslationHelper, which is messing with @i18n_scope

My workaround is to stop using you base class and manually just include WrappedHelper to ApplicationViewComponent, once switching to ViewComponent::Base from ViewComponentContrib::Base.

I would suggest to make it optional, as its breaking build in functionality of sidecar translations.

## Environment

**Ruby Version:**

3.2

**Framework Version (Rails, whatever):**

7.0.4 

**View Component Contrib Version:**

0.1.1

**Comment by palkan** [comment]
Thanks for reporting!

Looking at it.

**Comment by palkan** [comment]
Fixed and released in 0.1.2.
