### ISSUE TITLE
Upgrading to ViewComponents 3.0.0 and Lookbook 2.0 fails

### ISSUE THREAD

**Issue by raivil** [palkan/view_component-contrib#33]
## What did you do?
Upgraded lookbook gem (https://lookbook.build/guide/upgrading) from v1.x to v2.x.
Also using ViewComponents 3.0 (which is the real cause of the issue)
The app is running fine, only lookbook was affected (afaik).

## What did you expect to happen?
Lookbook not to fail :)

## What actually happened?
```
uninitialized constant ViewComponent::PreviewTemplateError

        rescue ViewComponent::PreviewTemplateError
                            ^^^^^^^^^^^^^^^^^^^^^^
Did you mean?  PreviewHelper
/installs/ruby/3.1.2/lib/ruby/gems/3.1.0/gems/view_component-contrib-0.1.3/lib/view_component_contrib/preview/default_template.rb [line 28]
```

![image](https://user-images.githubusercontent.com/2623565/235164541-981affc1-04e0-42a4-94d5-1df4ea1dd7ca.png)

## Additional context
The error is caused by ViewComponent upgrade to 3.0 (https://github.com/ViewComponent/view_component/compare/v2.82.0...v3.0.0)
where `lib/view_component/preview_template_error.rb` was removed.

## Environment

**Ruby Version:**
 ruby 3.1.2p20

**Framework Version (Rails, whatever):**
rails (7.0.4.3)

**View Component Contrib Version:**
  view_component (~> 3.0.0)
  view_component-contrib (~> 0.1.3)
lookbook (2.0.0)

**Comment by palkan** [comment]
Hey! This error has been fixed in master, can you please try it? I will release a new version as soon as I check if there are other incompatibilities with VC 3.0 and Lookbook 2.0

**Comment by palkan** [comment]
Ok, I found one more problem with this change and fixed it. Releasing 0.1.4
