### ISSUE TITLE
Rails 7.1 autoload_lib issue

### ISSUE THREAD

**Issue by igas** [palkan/view_component-contrib#39]
## What did you do?

Upgraded rails

## What did you expect to happen?

No errors due to the gem.

## What actually happened?

With new initializer:

```
config.autoload_lib(ignore: ["assets", "tasks"])
```

`lib/generators` not being ignored which causes errors.

## Additional context

I'm happy to send a PR, curious how would you want to handle it? Add docs in readme or adjust generator?

## Environment

**Ruby Version:** 3.2.2

**Framework Version (Rails, whatever):** 7.1.0.beta1

**View Component Contrib Version:** 0.1.4

**Comment by palkan** [comment]
I think, it should be fixed at the Rails side; `lib/generators` is pretty common.

@fxn Do you remember why you didn't included `generators` to the default ignore list? It's not clear from [the PR](https://github.com/rails/rails/pull/49032) (and previous PRs mentioned `generators` in multiple places).

**Comment by fxn** [comment]
Hey!

This was a tricky decision, indeed. I opted to generate the directories that the Rails application generator creates under `lib`.

There are common directories out there that could be ignored, like `lib/templates`, `lib/generators`, `lib/middlewares`, etc. You could always miss something in that list, and having all that generated by default without even existing seemed weird to me. Also, people could have legit namespaces in those subdirectories, you don't know in advance.

So, I opted for the subdirectories we know at generation time, and linked to the [docs](https://edgeguides.rubyonrails.org/autoloading_and_reloading_constants.html#config-autoload-lib-ignore) in a generated code comment just above the generated call.

I tend to lean also towards explicit APIs, so no hidden defaults.

Note that upgrading Rails does not get you `config.autoload_lib(ignore: ["assets", "tasks"])`. If the upgraded application has that line, it was written by someone, and you need to understand the call.

Open to improve this, however, after the user experience we see.

**Comment by fxn** [comment]
@igas did the application have `lib` in the autoload paths before?

**Comment by palkan** [comment]
> I opted to generate the directories that the Rails application generator creates under lib.

Totally makes sense. Thanks for the explanation @fxn !

I think, in our case, we should:

- Add a note to the documentation
- Inform a user to update their autoload_lib configuration (if any present) at the end of the installation script

**Comment by fxn** [comment]
After this discussion, I believe a code comment that explains the `ignore` list on the spot in `config/application.rb` is going to be more clear than a pointer to the docs. ([diff](https://github.com/rails/rails/commit/8eed5083b70d734ee9f16cb272fa1973b729353a#diff-907b37333a84c0b6faee93e22de9cca471e2bf8c66c8e13568f0bf508843186f))
