### ISSUE TITLE
Initializer script does nothing if user clicks enter on "Would you like to create a custom generator for your setup? (Recommended)"

### ISSUE THREAD

**Issue by fredrikburmester** [palkan/view_component-contrib#40]
## What did you do?
Ran the script `rails app:template LOCATION="https://railsbytes.com/script/zJosO5"` and pressed `efter` during the step `Would you like to create a custom generator for your setup? (Recommended)`.

## What did you expect to happen?
During the step `Would you like to create a custom generator for your setup? (Recommended)` i expect the default option to be `yes` when pressing `enter` since the step is recommended. At least the options (y/n) should be visible to the user.

## What actually happened?
The script did not create the folder `lib/generators/view_component`. Therefore `rails g view_component Example` did not work.

## Additional context
This seems like an easy fix in the script for a better user experience, since it took me a while to realise why the generators were not created. 

## Environment
MacOS Ventura 13.5
**Ruby Version:**
3.2.2
**Framework Version (Rails, whatever):**
Rails 7.0.8
**View Component Contrib Version:**
0.1.4

**Comment by palkan** [comment]
Thanks for the report!

Fixed
.
