### ISSUE TITLE
Variant style not compiled into stylesheet

### ISSUE THREAD

**Issue by nomasprime** [palkan/view_component-contrib#42]
## What did you do?

Add styles variant, as per readme.

## What did you expect to happen?

Tailwind to compile the variant.

## What actually happened?

Variant not compiled, ie, style missing.

## Environment

**Ruby Version:**

3.2.1

**Framework Version (Rails, whatever):**

7.1.3

**View Component Contrib Version:**

0.2.2

**Comment by nomasprime** [comment]
Tried in a vanilla Rails app, still doesn't work.

**Comment by palkan** [comment]
Could you please provide some code examples? It's hard to guess what do you mean by `Variant not compiled, ie, style missing.`

**Comment by nomasprime** [comment]
Sure, created a Rails app and followed the readme. Pushed repo [here](https://github.com/nomasprime/something).

**Comment by nomasprime** [comment]
Looks like install doesn't update tailwind config, looking into that on app I'm actually working on.

**Comment by nomasprime** [comment]
Looks like tailwind config set incorrectly: `'./app/views/**/*.{rb,erb,haml,html,slim}'`
