### ISSUE TITLE
Syntax error with Ruby 2.7

### ISSUE THREAD

**Issue by KeyAmam** [palkan/view_component-contrib#47]
## What did you do?

1. Include `ViewComponentContrib::StyleVariants` in a view component class
2. Load the class

## What did you expect to happen?

* The class is loaded

## What actually happened?

* The following error occurred:

```
syntax error, unexpected '='
...    def postprocess(compiled) = postprocessor.call(compiled)
...                              ^
/usr/local/bundle/gems/view_component-contrib-0.2.2/lib/view_component_contrib/style_variants.rb:211: syntax error, unexpected end-of-input, expecting `end'
```

## Additional context

* view_component-contrib is supposed to support Ruby >=2.7
  https://github.com/palkan/view_component-contrib/blob/fbec903198c2718cb97e432204344a22d1bf4e78/.rbnextrc#L3
* The endless (one-line) method definition used in `ViewComponentContrib::StyleVariants::StyleConfig` requires Ruby >=3.0
  https://github.com/palkan/view_component-contrib/blob/fbec903198c2718cb97e432204344a22d1bf4e78/lib/view_component_contrib/style_variants.rb#L178
* Fix the method definition or drop 2.7 support?

## Environment

**Ruby Version:** 2.7

**Framework Version (Rails, whatever):** 7.1.3

**View Component Contrib Version:** 0.2.2

**Comment by palkan** [comment]
Oh, my bad. It should have worked on Ruby 2.7, since we're using Ruby Next; but the transpiled filed were missing from the RubyGems package. Fixed in 0.2.3.
